# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('bookset', 'name')]),
        ),
    ]
