# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_account_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Debits: positive; Credits: negative.', max_digits=16),
        ),
    ]
